name: docker_compose
on: [ push ]
jobs:
  services:

    # Перечислим необходимые сервисы
    # В нашем случае их всего два: сервер и клиент

    server:
   
      # Указываем директорию, содержащую необходимый Dockerfile
      build: server/

      # Сам запуск сервера
      command: python ./server.py

      # Указываем, какие порты пробросить: -[порт компьютера]:[порт контейнера]
      ports:
        - 1111:1111

    # Второй сервис (контейнер): клиент.
    # Этот сервис назван 'client'.

    client:
      build: client/

      command: python ./client.py

      # Указываем тип сети
      # "host" позволяет сервису обращаться к localhost машины
      network_mode: host

      # Буквально задаем зависимости "данного" сервиса от каких-бы то ни было
      # Т.к. клиент без сервера работать не может, то подождем завершения запуска сервера 
      depends_on:
        - server